### ISSUE TITLE
AttributeError: module 'torch.distributed.rpc' has no attribute 'rpc_sync' when running tutorials

### ISSUE THREAD

**Issue by MarWaltz** [iffiX/machin#17]
Hello, when I am trying to run a tutorial script, e.g. the your_first_program example, I always encounter this AttributeError during the imports:

AttributeError: module 'torch.distributed.rpc' has no attribute 'rpc_sync'

However, I fulfill the listed requirements. Is there anything I am missing or have can I solve this?

**Comment by iffiX** [comment]
which version of torch and os platform are you using?

**Comment by MarWaltz** [comment]
torch version is 1.8.1+cu111 and my os is Windows 10, but I already tried several different torch versions.

**Comment by iffiX** [comment]
Yeah, windows torch does not support ``rpc_sync`` and any distributed model that is using this function (IMPALA, A3C, etc).
So far I don't have a windows platform to test so there might be some import errors. Could you please show the detailed error stack in python?

**Comment by MarWaltz** [comment]
Of course, see below:

Traceback (most recent call last):
  File "c:<file_path>.py", line 1, in <module>
    from machin.frame.algorithms import DQN
  File "C:\...\AppData\Local\Programs\Python\Python38\lib\site-packages\machin\__init__.py", line 1, in <module>
    from . import env, frame, model, parallel, utils
  File "C:\..\AppData\Local\Programs\Python\Python38\lib\site-packages\machin\env\__init__.py", line 1, in <module>
    from . import utils, wrappers
  File "C:\..\AppData\Local\Programs\Python\Python38\lib\site-packages\machin\env\wrappers\__init__.py", line 1, in <module>
    from . import base, openai_gym
  File "C:\..\AppData\Local\Programs\Python\Python38\lib\site-packages\machin\env\wrappers\openai_gym.py", line 8, in <module>
    from machin.parallel.exception import ExceptionWithTraceback
  File "C:\..\AppData\Local\Programs\Python\Python38\lib\site-packages\machin\parallel\__init__.py", line 2, in <module>
    from . import (
  File "C:\..\AppData\Local\Programs\Python\Python38\lib\site-packages\machin\parallel\distributed\__init__.py", line 1, in <module>
    from .world import (
  File "C:\..\AppData\Local\Programs\Python\Python38\lib\site-packages\machin\parallel\distributed\world.py", line 535, in <module>
    class RpcGroup:
  File "C:\..\AppData\Local\Programs\Python\Python38\lib\site-packages\machin\parallel\distributed\world.py", line 550, in RpcGroup
    @_copy_doc(rpc.rpc_sync)
AttributeError: module 'torch.distributed.rpc' has no attribute 'rpc_sync'

**Comment by iffiX** [comment]
Oh, that error is easy to fix, for now as a temporary fix you need to do the following changes:
In file https://github.com/iffiX/machin/blob/master/machin/parallel/__init__.py
1. Remove `` from . import distributed `` 
2. Remove ``"distributed"`` from ``__all__``
The wrapper you are using does not depend on rpc functions.

Please notify me if any other import errors persist.

**Comment by MarWaltz** [comment]
I did make these changes, but unfortunately I still run into the following:

Traceback (most recent call last):
  File "c:\<file_path>.py", line 1, in <module>
    from machin.frame.algorithms import DQN
  File "C:\..\AppData\Local\Programs\Python\Python38\lib\site-packages\machin\__init__.py", line 1, in <module>
    from . import env, frame, model, parallel, utils
  File "C:\..\AppData\Local\Programs\Python\Python38\lib\site-packages\machin\env\__init__.py", line 1, in <module>
    from . import utils, wrappers
  File "C:\..\AppData\Local\Programs\Python\Python38\lib\site-packages\machin\env\wrappers\__init__.py", line 1, in <module>
    from . import base, openai_gym
  File "C:\..\AppData\Local\Programs\Python\Python38\lib\site-packages\machin\env\wrappers\openai_gym.py", line 8, in <module>
    from machin.parallel.exception import ExceptionWithTraceback
  File "C:\..\AppData\Local\Programs\Python\Python38\lib\site-packages\machin\parallel\__init__.py", line 2, in <module>
    from . import (
  File "C:\..\AppData\Local\Programs\Python\Python38\lib\site-packages\machin\parallel\server\__init__.py", line 1, in <module>
    from . import ordered_server
  File "C:\..\AppData\Local\Programs\Python\Python38\lib\site-packages\machin\parallel\server\ordered_server.py", line 5, in <module>
    from ..distributed import RpcGroup
  File "C:\..\AppData\Local\Programs\Python\Python38\lib\site-packages\machin\parallel\distributed\__init__.py", line 1, in <module>
    from .world import (
  File "C:\..\AppData\Local\Programs\Python\Python38\lib\site-packages\machin\parallel\distributed\world.py", line 535, in <module>
    class RpcGroup:
  File "C:\..\AppData\Local\Programs\Python\Python38\lib\site-packages\machin\parallel\distributed\world.py", line 550, in RpcGroup
    @_copy_doc(rpc.rpc_sync)
AttributeError: module 'torch.distributed.rpc' has no attribute 'rpc_sync'

**Comment by iffiX** [comment]
Oh I forgot the "server", you also need to remove that. Sorry for this inconvenience.

**Comment by MarWaltz** [comment]
No worries. But still:

Traceback (most recent call last):
  File "c:\<file-path>.py", line 1, in <module>
    from machin.frame.algorithms import DQN
  File "C:\..\AppData\Local\Programs\Python\Python38\lib\site-packages\machin\__init__.py", line 1, in <module>
    from . import env, frame, model, parallel, utils
  File "C:\..\AppData\Local\Programs\Python\Python38\lib\site-packages\machin\frame\__init__.py", line 1, in <module>
    from . import algorithms, buffers, noise, transition
  File "C:\..\AppData\Local\Programs\Python\Python38\lib\site-packages\machin\frame\algorithms\__init__.py", line 3, in <module>
    from .dqn import DQN
  File "C:\..\AppData\Local\Programs\Python\Python38\lib\site-packages\machin\frame\algorithms\dqn.py", line 8, in <module>
    from machin.frame.buffers.buffer import Transition, Buffer
  File "C:\..\AppData\Local\Programs\Python\Python38\lib\site-packages\machin\frame\buffers\__init__.py", line 2, in <module>
    from .buffer_d import DistributedBuffer
  File "C:\..\AppData\Local\Programs\Python\Python38\lib\site-packages\machin\frame\buffers\buffer_d.py", line 5, in <module>
    from machin.parallel.distributed import RpcGroup
  File "C:\..\AppData\Local\Programs\Python\Python38\lib\site-packages\machin\parallel\distributed\__init__.py", line 1, in <module>
    from .world import (
  File "C:\..\AppData\Local\Programs\Python\Python38\lib\site-packages\machin\parallel\distributed\world.py", line 535, in <module>
    class RpcGroup:
  File "C:\..\AppData\Local\Programs\Python\Python38\lib\site-packages\machin\parallel\distributed\world.py", line 550, in RpcGroup
    @_copy_doc(rpc.rpc_sync)
AttributeError: module 'torch.distributed.rpc' has no attribute 'rpc_sync'

**Comment by iffiX** [comment]
OK for these errors you need to change the ``ImportError`` to ``Exception`` in these two files:
https://github.com/iffiX/machin/blob/master/machin/frame/algorithms/__init__.py
https://github.com/iffiX/machin/blob/master/machin/frame/buffers/__init__.py

Because AttributeError is not captured here.

**Comment by MarWaltz** [comment]
Okay thanks, I will have a look into it and come back to you tomorrow.

**Comment by iffiX** [comment]
No problem, I will correct these problem in my code now, and try to find a windows testing environment.

**Comment by MarWaltz** [comment]
Hello again, see below:

Traceback (most recent call last):
  File "c:\..\Desktop\Forschung\RL\Implementations\PyTorch Templates\machin\CartPole-DQN.py", line 1, in <module>
    from machin.frame.algorithms import DQN
  File "C:\..\AppData\Local\Programs\Python\Python38\lib\site-packages\machin\__init__.py", line 1, in <module>
    from . import env, frame, model, parallel, utils
  File "C:\..\AppData\Local\Programs\Python\Python38\lib\site-packages\machin\frame\__init__.py", line 1, in <module>
    from . import algorithms, buffers, helpers, noise, transition
  File "C:\..\AppData\Local\Programs\Python\Python38\lib\site-packages\machin\frame\algorithms\__init__.py", line 14, in <module>
    from .a3c import A3C
  File "C:\..\AppData\Local\Programs\Python\Python38\lib\site-packages\machin\frame\algorithms\a3c.py", line 2, in <module>
    from machin.parallel.server import PushPullGradServer
  File "C:\..\AppData\Local\Programs\Python\Python38\lib\site-packages\machin\parallel\server\__init__.py", line 1, in <module>
    from . import ordered_server
  File "C:\..\AppData\Local\Programs\Python\Python38\lib\site-packages\machin\parallel\server\ordered_server.py", line 5, in <module>
    from ..distributed import RpcGroup, debug_with_process
  File "C:\..\AppData\Local\Programs\Python\Python38\lib\site-packages\machin\parallel\distributed\__init__.py", line 1, in <module>
    from .world import (
  File "C:\..\AppData\Local\Programs\Python\Python38\lib\site-packages\machin\parallel\distributed\world.py", line 585, in <module>
    class RpcGroup:
  File "C:\..\AppData\Local\Programs\Python\Python38\lib\site-packages\machin\parallel\distributed\world.py", line 600, in RpcGroup
    @_copy_doc(rpc.rpc_sync)
AttributeError: module 'torch.distributed.rpc' has no attribute 'rpc_sync'

**Comment by iffiX** [comment]
OK, now move `from .a3c import A3C` to that try except block:
https://github.com/iffiX/machin/blob/baa093d85cfc578815e0adc85084f14abdbbd87d/machin/frame/algorithms/__init__.py#L23

**Comment by MarWaltz** [comment]
Great job, this example works fine now!
I will close this issue and open a new one if any further problems should occur.

Thanks again.

**Comment by iffiX** [comment]
OK, during this time I will add a quick fix to this when I got circleci working. :)

**Comment by iffiX** [comment]
After searching for a while I cannot find a platform with reasonable time for my auto testing, and since it is too difficult to maintain a hybrid jenkins-windows-vm setup I will not consider windows CI in the near future.

As a complement, I will do a one-time testing manually for requested future versions.

**Comment by oneoneonecy** [comment]
who can help me, blew:
 @rpc.functions.async_execution
AttributeError: module 'torch.distributed.rpc' has no attribute 'functions'

**Comment by oneoneonecy** [comment]
can help me that below:
 @rpc.functions.async_execution
AttributeError: module 'torch.distributed.rpc' has no attribute 'functions'
